### ISSUE TITLE
Discussion / Issue About Which Pages Or Posts Should Have Disqus Integrated

### ISSUE THREAD

**Issue by Rubix982** [Software-Development-Pakistan/Software-Development-Pakistan.github.io#22]
Just a issue to discuss which pages / posts we would like to see to have a disqus integration.

Complementary of PR #21

**Comment by azmaktr** [comment]
Awesome, I was thinking we can have comments for:

- easy way for people to contribute to career paths, learning resources,
- Ask more questions in FAQ

So lets try to have them in these to begin with ?

**Comment by azmaktr** [comment]
Disqus integrated! closing this now.
