### ISSUE TITLE
Learning Resources - Each subsection should have a unique URL/page

### ISSUE THREAD

**Issue by MuneebJS** [Software-Development-Pakistan/Software-Development-Pakistan.github.io#28]
From the readability and SEO perspective, it's good to have individual pages with unique URLs for each subsection.

Currently, **Learning Resources** has all the resources on one page. Ideally, each learning resource should have it's individual URL/page.

The URLs should look something like this _http://softdevpk.com/learning-resources/data-science_

**Comment by azmaktr** [comment]
each subsection already has a unique url: https://softdevpk.com/learning-resources/data-science/, or did you mean somehting else? @MuneebJS
