### ISSUE TITLE
University Official websites links are missing

### ISSUE THREAD

**Issue by MuneebJS** [Software-Development-Pakistan/Software-Development-Pakistan.github.io#29]
In the FAQ section, there is a question **Which university is better among the ones offering a relevant programme?**

Which has many universities listed but the hyperlink is missing for all the universities.

Ideally, each university title should redirect to their official website.

**Comment by Rubix982** [comment]
PR approved, merged, with #37, https://github.com/Software-Development-Pakistan/Software-Development-Pakistan.github.io/pull/37.
