### ISSUE TITLE
Add categories links to the Readme.md with any other basic details about the Repo

### ISSUE THREAD

**Issue by MuneebJS** [Software-Development-Pakistan/Software-Development-Pakistan.github.io#3]
Currently, `Readme.md` is almost empty with some dummy content.
We need to update readme.md with basic details about the repo and links to relevant files if required for instance **contribution guidelines**. 

More importantly, we need to link category files from the content table with an appropriate text in a structured way.

**Comment by Rubix982** [comment]
Added a "Getting Started" section in the README.md file, [here](https://github.com/Software-Development-Pakistan/Software-Development-Pakistan.github.io/blob/saif/README.md).

**Comment by Rubix982** [comment]
Done with current readme.md. Most probably, this should be closed now. Please open again if this needs to be?
