### ISSUE TITLE
Miscellanous Resources - Size of sub headings is too big

### ISSUE THREAD

**Issue by MuneebJS** [Software-Development-Pakistan/Software-Development-Pakistan.github.io#35]
The size of the subheading is too big to the extent that there seems to have no distinction between the main title and subheadings.

**Comment by Translucent504** [comment]
I can fix this and all related issues of subheading sizes. Should I edit [the general scss file](https://github.com/Software-Development-Pakistan/Software-Development-Pakistan.github.io/blob/be89f2b4d16e3c1016fc83bf07b9d7e5a403b9f6/_sass/imports/_general.scss#L51) Or should I just add a style for h2 on top of the [pages layout](https://github.com/Software-Development-Pakistan/Software-Development-Pakistan.github.io/blob/master/_layouts/page.html), The current sizes are : 
```
h1 {
  font-size: 2.22222em;
}

h2 {
  font-size: 1.88889em;
}

h3 {
  font-size: 1.55556em;
}

h4 {
  font-size: 1.33333em;
}

h5 {
  font-size: 1.11111em;
}

h6 {
  font-size: 0.88889em;
}
```

I can leave the h1 as it is and decrease the values for h2 and lower to:
```
h1 {
  font-size: 2.22222em;
}

h2 {
  font-size: 1.66667em;
}

h3 {
  font-size: 1.33333em;
}

h4 {
  font-size: 1.11111em;
}

h5 {
  font-size: 0.99999em;
}

h6 {
  font-size: 0.66667em;
}
```
# Before

> ![Before](https://user-images.githubusercontent.com/11474334/94728887-5c0a3b80-037a-11eb-9e26-1c363cc79d61.png)

# After
> ![After](https://user-images.githubusercontent.com/11474334/94728942-704e3880-037a-11eb-971d-a6287465e220.png)

**Comment by azmaktr** [comment]
Awesome! @Translucent504, can you send a PR?

**Comment by azmaktr** [comment]
Thanks @Translucent504 ! Really appreciate the contribution!
