### ISSUE TITLE
Fill content files with relevant stuff

### ISSUE THREAD

**Issue by MuneebJS** [Software-Development-Pakistan/Software-Development-Pakistan.github.io#4]
We might need to have a separate feature issue for each category. As a starting point, I'm keeping them in one but please comment if you think we should have a separate issue for each category file.

**Comment by Rubix982** [comment]
Made an FAQ with relative linking in md with some basic boiler plate content [here](https://github.com/Software-Development-Pakistan/Software-Development-Pakistan.github.io/blob/saif/Content/FAQ.md). 

We need a separate issue for getting ideas about what FAQs currently exist. Creating that.

**Comment by Rubix982** [comment]
Issue needs to be more detailed now.

CC, @azmaktr
