### ISSUE TITLE
Create contribution guidelines

### ISSUE THREAD

**Issue by MuneebJS** [Software-Development-Pakistan/Software-Development-Pakistan.github.io#5]
We need to create a contribution guideline that how a member of an organization or any individual can contribute to the repo.

We could look into the other open-source project but since the nature of our repo not quite different and we don't have many technical complexities so it would make more sense to have contribution guidelines as simple as possible.

Any suggestions are welcome if there are any similar well-known repositories doing the same thing as us, we could take inspiration from them.

**Comment by Rubix982** [comment]
Basic boiler plate Contribution Guidelines have been written [here](https://github.com/Software-Development-Pakistan/Software-Development-Pakistan.github.io/blob/saif/CONTRIBUTING.md).

**Comment by Rubix982** [comment]
Contribution Guidelines to be finalized with pull request #18
