### ISSUE TITLE
Add non-conventional career paths

### ISSUE THREAD

**Issue by husyn** [Software-Development-Pakistan/Software-Development-Pakistan.github.io#52]
### Problem
Atypical career paths in Software Engineering / Development are not mentioned in the current list.

### Solution
To add career paths like Scrum Master, Product Owner, Project Manager, Delivery Lead, Engineering Manager, Automation tester, Quality Analyst, Systems Analyst, Designer, Artist, etc. 

### Alternative
- Combine the above mentioned paths in some logical way to reduce the cardinality of career paths
- Have a defined boundaries of these paths and add mention these all in the career path with relevant differentiating content

### Context
Software development is not about writing _code_. It has lot of other areas like Human Computer Interaction (HCI), User Experience (UX), Interface designing (UI), and plethora of areas related to processes.

**Comment by Rubix982** [comment]
Pretty cool! We actually decided to move stuff like this into the `learning-resources/misc` file location. It currently has headings for `Mathematics` and `Data Structures` which don't really fit in the place like `career-paths`. 
I personally am still a student and don't have a complete idea and list of all the things you have mentioned, but would love to see your PR in the `learning-resources/misc` folder. Or do you recommend we place this somewhere else?

**Comment by husyn** [comment]
`Mathematics` and `Data Structures` are not really careers and yes should be part of learning-resources. These are the foundational concepts or topics which is required by a large number of computing related careers.

The things I've mentioned are clearly not topics or concepts but the career path themselves. You can have a career in Software development management which leads to Scrum Master -> Delivery Lead -> Engineering Manager -> CTO. Or similar path in Quality Assurance which is QA -> Sr QA -> Lead QA -> QA Manager. These non-programmer career paths should be defined and documented on their own IMHO.
